### ISSUE TITLE
Provide info about upcoming flow arrival not past flow arrival in state

### ISSUE THREAD

**Issue by stefanbschneider** [RealVNF/coord-sim#127]
Currently, we generate flows, schedule them directly according to the current scheduling rules, and then provide the average ingress traffic of the past run as state for the RL agent to decide the scheduling for the next run.

This works, probably, because the flow arrival is pretty static. Even in the MMP case it only changes every ~20 runs.

But the traffic of the upcoming run, for which the agent decides the scheduling could be completely different from the previous run. And the agent had no way of knowing it and making an appropriate decision.

It would be nice to assume, we have perfect traffic prediction and could know the flow arrival already head of time for the next run. And use that for the state rather than the flow arrival of the past run. That would be much more meaningful.

Rather than generating flows on the flow, we'll have to look into the future and get a list of the queued flow generation events in the next run. Technically, I'm not sure how/where to access the event queue. This should be helpful: https://simpy.readthedocs.io/en/latest/topical_guides/events.html

Maybe even easier: We handle this *before* SimPy. We generate flow arrivals up front in a long list. And then pass these flow arrivals to SimPy for flow generation - rather then generating the flow arrival then. This way, we already know when we'll generate new flows.

**Comment by qarawlus** [comment]
Why can't we make use of the trace feature that we implemented, and pass any possible trace as part of the state? 
It would certainly be much more limited as it is just one scenario, but it should give us a hint on whether or not passing future traffic is helpful in solving scenarios.

**Comment by stefanbschneider** [comment]
Good idea!

**Comment by qarawlus** [comment]
I have one question here: Should we have a toggle in the sim_config where we replace between past and future traffic? I am thinking that for at least deterministic scenarios, we can just compute the future ingress traffic and just pass that as the state instead of past ingress traffic state. 

This can be somewhat easily computed and would require changes only on the simulator's end. If we decide to pass the future traffic as additional information to the agent. 

Let me know how we you think we should proceed with this.

**Comment by stefanbschneider** [comment]
Since this is truly experimental, I'd simply create a new branch and change to providing the future traffic directly. No need to make it configurable yet. If it works, we'll make it nice. If it doesn't then we don't need to waste any time on configuration.

Let's focus, for now, only on deterministic traffic following a given traffic trace. This means:

* Create a scenario with varying traffic using a traffic trace: https://github.com/orgs/RealVNF/projects/1#card-35468960
* Test it with the current DDPG (combined reward) and see how it does. Probably not perfect? We first need to know limitations and an example of what we want to achieve
* Then adjust the simulator to read the trace files and compute the upcoming traffic in the next run instead of the traffic from the past run
* Debug if it works technically. Then experiment and see if it helps

**Comment by qarawlus** [comment]
I remembered one thing, we conducted a lot of experiments with no input state. We were able to solve a lot of scenarios with the no-state branch. Wouldn't passing an incorrect state also yield the same result as a no state? I am just asking this to make sure that we don't get a false positive if the future traffic tweak does indeed work technically.

**Comment by stefanbschneider** [comment]
That was on scenarios with static traffic. Usually with a single best placement that was learned just by feedback from the reward - independent from the state.

Now, we're looking for a scenario with more dynamic traffic, where there the best placement changes depending on the traffic.
To make sure, you can first test this a) with our current agent and state and b) without any state. I don't expect that to work very well (at least not to find dynamically changing placements).
Here, the future traffic in the state should help.

**Comment by qarawlus** [comment]
After some back-of-the hand calculation. I have chosen the single ingress rand-cap 0-2 Abilene network with the following traffic trace. 
|  time     | inter_arrival_mean |
| :---: | :---: | 
| 0 | 10 |
| 6500 | 5 |
| 13000 | 1 |

The network will have capacity to serve requests at the first node until step 6500. Afterwards, the flows will have to be distributed. The next node can handle the remaining flows until step 13000. Then, the flows will have to be even more distributed. I am currently testing this with the master branch agent to see what the results are.

**Comment by stefanbschneider** [comment]
I added an explanation of the new delay reward for scenario01 here: https://github.com/RealVNF/evaluation-netai2020/tree/master/triangle/scenario01#new-delay-reward

Does this help? I'm happy to clarify it further.

**Comment by qarawlus** [comment]
I have created a PR to add the prediction module to the simulator. 

Initial results are very promising. After a 10x 100 episode training and testing, this is the learning curve the agent receives on a pure flow reward with a changing capacity scenario:
![image](https://user-images.githubusercontent.com/44025202/78512104-20fbc680-77a2-11ea-8680-f35044cc15df.png)

The agent with no traffic prediction has the following learning curve for the same configuration
![image](https://user-images.githubusercontent.com/44025202/78512121-56081900-77a2-11ea-88be-a08d389e7356.png)

It is very clear that many agents quickly find the solution with future traffic passed in the state. The agents with current traffic stay in a lower reward range for a longer time.

I am currently running tests with a delay reward scenario to test that as well.

**Comment by qarawlus** [comment]
With F1D3 scenario:

With prediction:
![image](https://user-images.githubusercontent.com/44025202/78512806-c06f8800-77a7-11ea-9fca-d65ac5d36b59.png)

Without prediction:
![image](https://user-images.githubusercontent.com/44025202/78513009-f7926900-77a8-11ea-884b-b906e8e2fb86.png)

**Comment by stefanbschneider** [comment]
Nice findings,  they look really promising!

**Comment by stefanbschneider** [comment]
The ultimate goal would be traffic prediction (with ML + comparison with ground truth "prediciton" + comparison without any prediction) on the Abilene traffic traces. But rather than going straight to that, let's gradually increase scenario complexity and see what happens. 

How about 2 ingress nodes (you currently had one, right?) and traffic that goes up and down 2-3x such that with fixed cap and combined flow & delay reward (weights 0.5, 0.5) the agent should learn to move instances back and forth between the ingress nodes.

Feel free to close this issue and create a new one in the evaluation repo for that. 👍

**Comment by stefanbschneider** [comment]
There seems to be some issue with Travis: https://travis-ci.org/github/RealVNF/coord-sim

**Comment by qarawlus** [comment]
https://travis-ci.com/github/RealVNF/coord-sim 

For me here Travis is showing that build has passed!

**Comment by stefanbschneider** [comment]
ok weird
