### ISSUE TITLE
Switch states independently for each ingress (MMP)

### ISSUE THREAD

**Issue by stefanbschneider** [RealVNF/coord-sim#128]
Currently, in MMP scenarios, all ingress nodes are always in the same state (high or low traffic) and switch the state together.

Doesn't really make sense. Ingress nodes should switch state independently from each other.

**Comment by qarawlus** [comment]
I moved this to "To-do" in order to do some parallel work while Adnan experiments with traffic prediction. This is straightforward to complete and shouldn't take much time to complete.
