### ISSUE TITLE
Visualize Placement

### ISSUE THREAD

**Issue by stefanbschneider** [RealVNF/coord-sim#154]
Especially in large networks, it's really tedious to read the placement file and understand what an algorithm did.

We should add support for visualizing placements (eg, after the last run).

Use NetworkX features for that: https://networkx.github.io/documentation/stable/reference/drawing.html
Either draw it with matplotlib or export it and use Cytoscape.

It should basically show the network topology, the ingress nodes (with rate?) and the placed VNFs. It should also show the node ID and capacity of all nodes. Optionally also the used resources, routes and schedule, but that's less important for now.

Would make analyzing large placements much easier!

**Comment by qarawlus** [comment]
I have created a visualization prototype for the placement in this notebook https://github.com/RealVNF/evaluation-netai2020/blob/master/resubmission/scalability_new_networks_600k/eval.ipynb

It has some limitations:
- It randomly selects a seed from one of the best agents to show placement. For algorithms, it just selects one of the iteration seeds.
- It plots placement over all networks for one algorithm. 
- Plot is for a specified simulator run, defined in a variable.
- NX drawing is slow by nature

**Comment by stefanbschneider** [comment]
Looks good for a first prototype. If it's very slow, I'd probably keep it outside of our standard eval notebook and have it in a separate script or notebook.

Did you check Cytoscape on https://networkx.github.io/documentation/stable/reference/drawing.html ?
It seems like that could read Graphml files produced by NX and allow interactive plotting with colored nodes. That could help to choose different colors for ingress nodes and nodes with placement for example.

**Comment by stefanbschneider** [comment]
I guess it makes most sense to add this to the eval notebook in the RL repo. Then we can use it easily when checking new RL results.

Then you can also close this issue

**Comment by qarawlus** [comment]
I have checked the possibility of using Cytoscape. It's a standalone tool that we have install and use separately. I do not believe it can be integrated into our current notebook process.

**Comment by stefanbschneider** [comment]
I know, it wouldn't have to be integrated. It would be a separate workflow using the separate tool - if we need it. 

But since, we're not debugging anymore and don't currently need it, let's just stick with the workflow that you implemented.

**Comment by qarawlus** [comment]
If I copy this into the rl-coordination repo, it will make it slower as well since we now have a big placement notebook that stores all placement at all timesteps. I think that it would be better to keep this as a separate notebook in the rl repo and just use it when need to visualize placement. After all, if we use Jupyter Lab, it shouldn't take more than a couple of clicks to run it separately.

**Comment by stefanbschneider** [comment]
Ok, agreed. But it should be very easy to find with a reference from the readme in https://github.com/RealVNF/evaluation
